[package]
name = "lendpool"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-queue = { version = "0.3.12" }

# features async
tokio = { version = "1.42.0" ,features = ["sync"], optional = true }



[features]
default = []
sync = []
async = ["tokio"]
